<section class="pt-20 lg:pt-0 w-8/12 pl-3">
    <h1>Visi dan Misi</h1>
    <h4>
        <strong> Visi </strong>
    </h4>
    <p>
        <span style="font-weight: normal;">TERWUJUDNYA SEKOLAH SEBAGAI PUSAT PENDIDIKAN BERWAWASAN LINGKUNGAN YANG MAMPU MEMBENTUK MANUSIA YANG UNGGUL DALAM BIDANG AKADEMIK DAN NON AKADEMIK DILANDASI IMTAQ IPTEK, DAN SENI SERTA BERBUDAYA LINGKUNGAN YANG SEHAT</span>
    </p>

    <h4>
        <strong> Misi </strong>
    </h4>
    <ol>
        <li>1. MENINGKATKAN KARAKTER PESERTA DIDIK YANG BERIMAN, BERTAQWA KEPADA TUNAN YANG MAHA ESA DAN BERAKHLAK MULIA</li>
        <li>2. MENUMBUHKAN SEMANGAT GOTONG ROYONG PADA PESERTA DIDIK</li>
        <li>3. MENGEMBANGKAN KARAKTER PESERTA DIDIK YANG MANDIRI, KREATIF DAN BERNALAR KRITIS SEHINGGA MAMPU MENGHASILKAN IDE DAN KETERAMPILAN YANG INOVATIF</li>
        <li>4. MENCIPTAKAN LINGKUNGAN BERSIN, HIJAU, SEJUK, AMAN DAN NYAMAN BERWAWASAN WIYATA MANDALA</li>
        <li>5. MEMBUDAYAKAN LITERASI MELALUI PROGRAM INTRAKURIKULER DAN PROJECT PROFIL PELAJAR PANCASILA</li>
        <li>6. MENGEMBANGKAN POTENSI DIRI PESERTA DIDIK MENJADI MANUSIA TANGGUN MENGHADAPI PERSAINGAN GLOBAL DENGAN MEMANFAATKAN KEMAJUAN TEKNOLOGI INFORMASI DAN KOMUNIKASI</li>
    </ol>

</section>