<section class="pt-20 lg:pt-0 w-8/12 pl-5">
    <h1>Visi dan Misi</h1>
    <h4>
        <strong> Visi </strong>
    </h4>
    <p class="normal-case pl-6">TERWUJUDNYA SEKOLAH SEBAGAI PUSAT PENDIDIKAN BERWAWASAN LINGKUNGAN YANG MAMPU MEMBENTUK MANUSIA YANG UNGGUL DALAM BIDANG AKADEMIK DAN NON AKADEMIK DILANDASI IMTAQ IPTEK, DAN SENI SERTA BERBUDAYA LINGKUNGAN YANG SEHAT</p>

    <h4>
        <strong> Misi </strong>
    </h4>
    <ol class="list-decimal">
        <li>MENINGKATKAN KARAKTER PESERTA DIDIK YANG BERIMAN, BERTAQWA KEPADA TUNAN YANG MAHA ESA DAN BERAKHLAK MULIA</li>
        <li>MENUMBUHKAN SEMANGAT GOTONG ROYONG PADA PESERTA DIDIK</li>
        <li>MENGEMBANGKAN KARAKTER PESERTA DIDIK YANG MANDIRI, KREATIF DAN BERNALAR KRITIS SEHINGGA MAMPU MENGHASILKAN IDE DAN KETERAMPILAN YANG INOVATIF</li>
        <li>MENCIPTAKAN LINGKUNGAN BERSIN, HIJAU, SEJUK, AMAN DAN NYAMAN BERWAWASAN WIYATA MANDALA</li>
        <li>MEMBUDAYAKAN LITERASI MELALUI PROGRAM INTRAKURIKULER DAN PROJECT PROFIL PELAJAR PANCASILA</li>
        <li>MENGEMBANGKAN POTENSI DIRI PESERTA DIDIK MENJADI MANUSIA TANGGUN MENGHADAPI PERSAINGAN GLOBAL DENGAN MEMANFAATKAN KEMAJUAN TEKNOLOGI INFORMASI DAN KOMUNIKASI</li>
    </ol>

</section>